import { chartSchema, role } from "./schemaTypes.js";
const form = { sections: ["data", "appearance", "labels", "targets", "collection", "interactions", "advanced"] }; const capabilities = { timeSync: true, collection: true, zoom: false }; const time = () => role("time", "Time", ["temporal"], 0);
export const targetSchemas = [
  chartSchema({ typeId: "kpi", label: "KPI card", group: "targets", description: "Display one key measurement with optional context.", sources: ["dataset", "inline"], roles: [role("value", "Value", ["number"], 1), role("target", "Target", ["number"], 0), time()], form, dataFamily: "target", renderer: "target", capabilities, conversions: ["gauge", "bullet", "deltaCard"], manualData: { maxRows: 20 }, semantics: { purpose: "status", mark: "kpi" } }),
  chartSchema({ typeId: "gauge", label: "Gauge", group: "targets", description: "Show a current value against configured threshold ranges.", sources: ["dataset", "inline"], roles: [role("value", "Value", ["number"], 1), role("target", "Target", ["number"], 0), time()], form, dataFamily: "target", renderer: "target", capabilities, conversions: ["kpi", "bullet"], manualData: { maxRows: 20 }, semantics: { purpose: "status", mark: "gauge" } }),
  chartSchema({ typeId: "bullet", label: "Bullet / target", group: "targets", description: "Compare actual performance against a target and performance ranges.", sources: ["dataset", "inline"], roles: [role("actual", "Actual", ["number"], 1), role("target", "Target", ["number"], 1), role("label", "Label", ["text", "category"], 0), time()], form, dataFamily: "target", renderer: "target", capabilities, conversions: ["kpi", "gauge"], manualData: { maxRows: 20 }, semantics: { purpose: "target", mark: "bullet" } }),
  chartSchema({ typeId: "deltaCard", label: "Delta card", group: "targets", description: "Show change between observations for a single measurement.", sources: ["dataset", "inline"], roles: [role("measurement", "Measurement", ["number"], 1), role("entity", "Entity", ["category", "text"], 0), role("time", "Time", ["temporal"], 1), role("target", "Target", ["number"], 0)], form, dataFamily: "target", renderer: "target", capabilities, conversions: ["deltaList", "kpi"], manualData: { maxRows: 20 }, semantics: { purpose: "change", mark: "delta-card" } }),
  chartSchema({ typeId: "deltaList", label: "Delta list", group: "targets", description: "Compare change across multiple entities.", roles: [role("measurement", "Measurement", ["number"], 1), role("entity", "Entity", ["category", "text"], 1), role("time", "Time", ["temporal"], 1), role("target", "Target", ["number"], 0)], form, dataFamily: "target", renderer: "target", capabilities, conversions: ["deltaCard"], semantics: { purpose: "change", mark: "delta-list" } }),
];
